version: 2.1

orbs: 
  docker: circleci/docker@2.1.2

jobs:
  build-and-deploy:

workflows:
  main:
    jobs:
      - docker/publish:
          image: bufferings/cimg-cue
          tag: latest,$CIRCLE_SHA1
          remote-docker-version: 20.10.12
          update-description: false
          use-buildkit: true
          filters:
            branches:
              only: main
